import { University, VisaChecklistItem, GradePointsMap } from '@/types';

// Living cost constant for 2026 (DHA requirement)
export const LIVING_COST_AUD = 29710;
export const TRAVEL_COST_AUD = 2500;

// KCSE Grades
export const KCSE_GRADES = ['A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D', 'D-', 'E'];

// Grade to Points mapping
export const GRADE_POINTS: GradePointsMap = {
  'A': 12,
  'A-': 11,
  'B+': 10,
  'B': 9,
  'B-': 8,
  'C+': 7,
  'C': 6,
  'C-': 5,
  'D+': 4,
  'D': 3,
  'D-': 2,
  'E': 1,
};

// Sample Universities Data
export const UNIVERSITIES: University[] = [
  {
    id: 1,
    name: 'University of Adelaide',
    city: 'Adelaide',
    state: 'SA',
    isRegional: true,
    pswBonus: 2,
    avgTuition: 38000,
    cricos: '00123M',
    ranking: 89,
    courses: ['Engineering', 'Business', 'IT', 'Health Sciences', 'Agriculture', 'Law'],
  },
  {
    id: 2,
    name: 'Curtin University',
    city: 'Perth',
    state: 'WA',
    isRegional: true,
    pswBonus: 2,
    avgTuition: 32000,
    cricos: '00301J',
    ranking: 193,
    courses: ['Mining Engineering', 'Business', 'IT', 'Nursing', 'Architecture'],
  },
  {
    id: 3,
    name: 'Griffith University',
    city: 'Gold Coast',
    state: 'QLD',
    isRegional: true,
    pswBonus: 1,
    avgTuition: 31000,
    cricos: '00233E',
    ranking: 290,
    courses: ['Tourism', 'Business', 'IT', 'Health', 'Environmental Science'],
  },
  {
    id: 4,
    name: 'University of Melbourne',
    city: 'Melbourne',
    state: 'VIC',
    isRegional: false,
    pswBonus: 0,
    avgTuition: 45000,
    cricos: '00116K',
    ranking: 14,
    courses: ['Law', 'Medicine', 'Engineering', 'Arts', 'Commerce', 'Science'],
  },
  {
    id: 5,
    name: 'University of Sydney',
    city: 'Sydney',
    state: 'NSW',
    isRegional: false,
    pswBonus: 0,
    avgTuition: 46000,
    cricos: '00026A',
    ranking: 19,
    courses: ['Business', 'Engineering', 'Medicine', 'Law', 'Architecture'],
  },
  {
    id: 6,
    name: 'Deakin University',
    city: 'Geelong',
    state: 'VIC',
    isRegional: true,
    pswBonus: 1,
    avgTuition: 33000,
    cricos: '00113B',
    ranking: 266,
    courses: ['Nursing', 'IT', 'Business', 'Education', 'Sports Science'],
  },
  {
    id: 7,
    name: 'University of Tasmania',
    city: 'Hobart',
    state: 'TAS',
    isRegional: true,
    pswBonus: 2,
    avgTuition: 30000,
    cricos: '00586B',
    ranking: 293,
    courses: ['Marine Science', 'IT', 'Business', 'Agriculture', 'Antarctic Studies'],
  },
  {
    id: 8,
    name: 'James Cook University',
    city: 'Townsville',
    state: 'QLD',
    isRegional: true,
    pswBonus: 2,
    avgTuition: 29000,
    cricos: '00117J',
    ranking: 461,
    courses: ['Marine Biology', 'Nursing', 'IT', 'Tourism', 'Veterinary Science'],
  },
  {
    id: 9,
    name: 'University of Queensland',
    city: 'Brisbane',
    state: 'QLD',
    isRegional: false,
    pswBonus: 0,
    avgTuition: 42000,
    cricos: '00025B',
    ranking: 43,
    courses: ['Engineering', 'Business', 'Medicine', 'Science', 'Agriculture'],
  },
  {
    id: 10,
    name: 'Flinders University',
    city: 'Adelaide',
    state: 'SA',
    isRegional: true,
    pswBonus: 2,
    avgTuition: 31000,
    cricos: '00114A',
    ranking: 380,
    courses: ['Medicine', 'Nursing', 'Education', 'Social Work', 'IT'],
  },
  {
    id: 11,
    name: 'University of Western Australia',
    city: 'Perth',
    state: 'WA',
    isRegional: true,
    pswBonus: 2,
    avgTuition: 39000,
    cricos: '00126G',
    ranking: 72,
    courses: ['Engineering', 'Law', 'Medicine', 'Business', 'Science'],
  },
  {
    id: 12,
    name: 'UNSW Sydney',
    city: 'Sydney',
    state: 'NSW',
    isRegional: false,
    pswBonus: 0,
    avgTuition: 47000,
    cricos: '00098G',
    ranking: 19,
    courses: ['Engineering', 'Business', 'Law', 'Medicine', 'Design'],
  },
];

// Visa Checklist Items
export const VISA_CHECKLIST: VisaChecklistItem[] = [
  {
    id: 1,
    item: 'Valid passport',
    description: 'Must be valid for the entire duration of your intended stay in Australia',
    mandatory: true,
  },
  {
    id: 2,
    item: 'Confirmation of Enrolment (CoE)',
    description: 'Electronic confirmation from your registered Australian education provider',
    mandatory: true,
  },
  {
    id: 3,
    item: 'Genuine Student statement',
    description: 'Written statement addressing the Genuine Student requirements',
    mandatory: true,
  },
  {
    id: 4,
    item: 'Financial capacity evidence',
    description: 'Bank statements, sponsor letters, scholarship letters, or loan approvals',
    mandatory: true,
  },
  {
    id: 5,
    item: 'English proficiency results',
    description: 'IELTS, PTE Academic, or TOEFL iBT score report (valid for 2 years)',
    mandatory: true,
  },
  {
    id: 6,
    item: 'Overseas Student Health Cover (OSHC)',
    description: 'Health insurance policy covering the entire duration of your student visa',
    mandatory: true,
  },
  {
    id: 7,
    item: 'Academic transcripts',
    description: 'KCSE certificate, academic transcripts, and any other qualifications',
    mandatory: true,
  },
  {
    id: 8,
    item: 'Police clearance certificate',
    description: 'Certificate of Good Conduct from Kenya Police (if 16 years or older)',
    mandatory: true,
  },
  {
    id: 9,
    item: 'Health examination',
    description: 'Medical exam from an approved panel physician (may be requested)',
    mandatory: false,
  },
  {
    id: 10,
    item: 'Proof of accommodation',
    description: 'Booking confirmation for first 4 weeks of accommodation in Australia',
    mandatory: false,
  },
  {
    id: 11,
    item: 'Birth certificate',
    description: 'Original or certified copy of your birth certificate',
    mandatory: false,
  },
  {
    id: 12,
    item: 'Passport photos',
    description: 'Recent passport-sized photographs (45mm x 35mm)',
    mandatory: false,
  },
];

// Kenya Counties for dropdown
export const KENYA_COUNTIES = [
  'Baringo', 'Bomet', 'Bungoma', 'Busia', 'Elgeyo-Marakwet', 'Embu', 'Garissa',
  'Homa Bay', 'Isiolo', 'Kajiado', 'Kakamega', 'Kericho', 'Kiambu', 'Kilifi',
  'Kirinyaga', 'Kisii', 'Kisumu', 'Kitui', 'Kwale', 'Laikipia', 'Lamu', 'Machakos',
  'Makueni', 'Mandera', 'Marsabit', 'Meru', 'Migori', 'Mombasa', 'Murang\'a',
  'Nairobi', 'Nakuru', 'Nandi', 'Narok', 'Nyamira', 'Nyandarua', 'Nyeri',
  'Samburu', 'Siaya', 'Taita-Taveta', 'Tana River', 'Tharaka-Nithi', 'Trans-Nzoia',
  'Turkana', 'Uasin Gishu', 'Vihiga', 'Wajir', 'West Pokot',
];
